### ISSUE TITLE
Deprecated feature ;(

### ISSUE THREAD

**Issue by nouranahmed-3** [nouranahmed2003/Double-pendulum-SCSS2023#17]
![image](https://user-images.githubusercontent.com/130341693/232074848-45c2f252-9c68-4d41-a4b7-d6d8babc9242.png)

Idk what it is in the code, I've already removed the center tags but there's still something there. As for the audit usage comment it's something to do with the links used in src when it outsources p5.js links

**Comment by laiadriantao** [comment]
@nouranahmed2003 if this is related to the latest PR I will look into it
