### ISSUE TITLE
Regarding Latest Issue

### ISSUE THREAD

**Issue by laiadriantao** [nouranahmed2003/Double-pendulum-SCSS2023#20]
![image](https://user-images.githubusercontent.com/80288583/232111235-99aaac4d-1872-4ae5-a491-daac61899270.png)
This error is insignificant to our project. Also, the pendulum behaves very much like a simple pendulum with the values you've provided. If I am wrong please let me know @nouranahmed2003

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232111687-b7250883-3caf-446d-a4b2-12a9ee5b40b2.png)
![image](https://user-images.githubusercontent.com/80288583/232111746-a8d2487b-3068-491e-899b-b731ecf17804.png)
![image](https://user-images.githubusercontent.com/80288583/232111852-564719dd-aabb-4342-a706-29f42afa675e.png)

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232112377-41fa7ee7-4540-4d3e-8b44-c7f5c531248b.png)
What we are looking for

**Comment by nouranahmed-3** [comment]
Yeah you're right, I see your point After playing around with the values a bit, there's a bit of an issue with regards to the damping. It won't spiral out of control if we have the damping and a g value that isn't too great but it won't give you the pattern above. If we want the pattern above (which ideally we do) then I see no sense in including damping unfortunately even though realistically it would stop at some point, it would be easier to not factor it in at all. It has the initial pattern above before it "focuses" (for a lack of better words) more on the bottom line of the curve.
![image](https://user-images.githubusercontent.com/130341693/232121463-fe3ba61d-3be7-4e35-afce-e90e0caedddd.png)
=> with damping we don't get to see the chaotic motion because it's slowed down way too quickly and doesn't give us a chance to see it
=> without damping it'll never stop and it's a bit unrealistic but I think we can keep thinking abt it and just ignore it
What do you think @laiadriantao ?

**Comment by laiadriantao** [comment]
@nouranahmed2003 I think we should not use damping from now on. But also, from what I know we are working with radians instead of degrees. Just by my recent statement, what do you think of the results of our formulas? Would we get it differrent if we work in degrees instead of radians?

**Comment by laiadriantao** [comment]
I am going to try and see what I can do about the degrees part

**Comment by nouranahmed-3** [comment]
In theory it should be the same, it's mainly an issue of how the program and the output sees the angles with its axis as opposed to what we define them to be as angles if that makes sense. Remember how at MEM he told us degrees are basically just a construct but radians are actually the measurement? With regards to input from the user to be used later on in the program, we can manually make the change into radians.

**Comment by nouranahmed-3** [comment]
P.S. That's a really good observation though, nice! 😮

**Comment by laiadriantao** [comment]
With that in mind, I think we are okay with radians, but I am curious asf to try degrees out hahahahahah

**Comment by nouranahmed-3** [comment]
Oooo, ok! I hope it works out! I’ll see if there’s something I can do to possibly help as well ~

**Comment by nouranahmed-3** [comment]
If you manually change to rad it works just the same (you probably figured it out deja but still)
![image](https://user-images.githubusercontent.com/130341693/232126344-a7debd3c-5f38-420c-9b38-541ac99bfe78.png)

**Comment by laiadriantao** [comment]
@nouranahmed2003 did you do *Change for every single sin and cos? I got as far as trying out another library  lol

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232130882-1e7a1051-a239-4aae-a1c0-683aa8c8ca19.png)
it's chaotic for a while then it behaves almost like a simple pendulum

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232131054-017667c9-0e2f-45a5-85eb-dd4ac6db0396.png)
nvm...

**Comment by nouranahmed-3** [comment]
No I didn't do it for all but seeing as the angle used in calculations is in rad, simply multiplying by "change" a1, and a2 the rest of the calculations should in theory remain unchanged cos we're still working in rad, I didn't go as far as to actually work in degrees rather I made it possible for the input to be in degrees and have that be used in rad by the program

**Comment by nouranahmed-3** [comment]
> ![image](https://user-images.githubusercontent.com/80288583/232130882-1e7a1051-a239-4aae-a1c0-683aa8c8ca19.png) it's chaotic for a while then it behaves almost like a simple pendulum

It always has the look of a simple pendulum at some point even if it goes awry after that

**Comment by laiadriantao** [comment]
NOURAN LOOK 
![image](https://user-images.githubusercontent.com/80288583/232132110-5205c05c-5640-44df-9617-8b84a568ceb7.png)

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232132179-04261fba-7246-458b-aab9-632e2215e48c.png)

**Comment by laiadriantao** [comment]
![image](https://user-images.githubusercontent.com/80288583/232132272-125691e8-8d8a-4d43-8a2b-a4b68b0395a1.png)
slowly stopping, but still moving

**Comment by nouranahmed-3** [comment]
That's insane!! 😮

**Comment by laiadriantao** [comment]
wait imma do a PR @nouranahmed2003

**Comment by laiadriantao** [comment]
@nouranahmed2003 how do you feel about it?

**Comment by nouranahmed-3** [comment]
I didn’t mind working in rad so the angle change doesn’t matter calculation wise very much to me ( although it is very cool!! ) but I’m glad the overall pendulum is making the motion it’s supposed to be making and great job on making the dampening work!!! We could just say the scale is 1:10 for g until we figure smthg else out and we can run it by the prof to see if he’s fine with that

**Comment by laiadriantao** [comment]
Oh yeah I totally forgot about g

**Comment by laiadriantao** [comment]
are we keeping it in rads tho?
@nouranahmed2003

**Comment by laiadriantao** [comment]
Like what do you think?

**Comment by nouranahmed-3** [comment]
We can keep it in degrees since you already made the change, there’s no sense in turning it back unless we face any issues (which I don’t think we will regarding this). I think we can move forward and work on the rest of the elements of the project. Do you agree with this?

**Comment by laiadriantao** [comment]
Yes!!!
