### ISSUE TITLE
Button suggestions

### ISSUE THREAD

**Issue by laiadriantao** [nouranahmed2003/Double-pendulum-SCSS2023#26]
From my personal point of view I think that we should keep all the values we have right now and just add variables for each parameter that will influence the movement of the pendulum. 

Example: g = 0.981 * inputValueForG

I am also thinking of trying out the mass at 100 instead of 1000 or something less than 1000 anyways. I was thinking of giving you full autonomy over the buttons, idk why honestly. It was just a thought. Let me know what your wishes are.

Note: worry about aesthetics later. Functionality first!

**Comment by nouranahmed-3** [comment]
I like the idea for g (although it might make it spiral out of control if the user input isn't a 1,2,3 but an actual value for g, ex: 0.981*9.81 -> the program would use 9.62), I was thinking for the angles to change them completely to what the input value is though.

Yeah it would be interesting to see how different masses react too. As for the buttons, I'll try my best to make them work along with the input, I'll ask questions when I need help of course, I'm hoping they'll work without you having to change too much so it's not like you're doing double the work if that makes sense.

 Would you prefer the angle values to be input by use of a button or by manually dragging the masses of the pendulum manually? Ideally we can have both, I was thinking of doing it by use of a button at first and then we can add the drag feature. What do you think?

**Comment by laiadriantao** [comment]
It's not necessary to work with g, it was just an example. Have fun!

Would you prefer the angle values to be input by use of a button or by manually dragging the masses of the pendulum manually? 

> Well, here I have no preference. Do as you wish (:

Ideally we can have both, I was thinking of doing it by use of a button at first and then we can add the drag feature. 
What do you think?

> I felt like you read my thoughts on this one. You can stop at the input box and focus on something else before we do anything fancy such as mouse dragging the bar elements.

I will post some ideas for your mind to munch on.

- [ ] refresh button (ik we have it already)
- [ ] pause button
- [ ] pause button implies continue button
- [ ] when one parameter is changed the drawing/animation should reset and start with those valies
- [ ] it would be interesting to have the animation start by button rather than it starting right when the program turns on
- [ ] textboxes > sliders for obvious reasons eg. precision
- [ ] i'll let you think about which deserves a textbox or not wrt the "physical" values

@nouranahmed2003 don't stress over it also. I'd rather have you ask me instead of going into a stackoverflow, documentation and youtube rabbit hole.  GLHF nouran, msg me any time. If you do it here @ me.
